<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>aef0423a-9a3e-406a-bfdf-870fc04fab7e</UserSecretsId>
	</PropertyGroup>

  <ItemGroup>
    <Content Remove="Properties\launchSettings.json" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Properties\launchSettings.json" />
  </ItemGroup>

	<ItemGroup>
		<PackageReference Include="Hangfire" Version="1.8.23" />
		<PackageReference Include="Hangfire.AspNetCore" Version="1.8.23" />
		<PackageReference Include="Hangfire.SqlServer" Version="1.8.23" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.5" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.5">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.7" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\AuthApi.Application\AuthApi.Application.csproj" />
	  <ProjectReference Include="..\AuthApi.Infrastructure\AuthApi.Infrastructure.csproj" />
	</ItemGroup>

</Project>
