<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>d5174335-ab90-4d4e-b3c9-3baa55ce8d52</UserSecretsId>
  </PropertyGroup>

	<ItemGroup>
		<AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
			<_Parameter1>AuthApi.IntegrationTests</_Parameter1>
		</AssemblyAttribute>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Dapper" Version="2.1.72" />
		<PackageReference Include="DnsClient" Version="1.8.0" />
		<PackageReference Include="Hangfire" Version="1.8.23" />
		<PackageReference Include="Hangfire.AspNetCore" Version="1.8.23" />
		<PackageReference Include="Hangfire.Core" Version="1.8.23" />
		<PackageReference Include="Hangfire.Redis.StackExchange" Version="1.12.0" />
		<PackageReference Include="Mapster" Version="10.0.7" />
		<PackageReference Include="Mapster.DependencyInjection" Version="10.0.7" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.5" />
		<PackageReference Include="Microsoft.AspNetCore.SignalR.StackExchangeRedis" Version="10.0.6" />
		<PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.5" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.5" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.5" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.5" />
		<PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="10.0.6" />
		<PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.5" />
		<PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="6.0.1" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.5" />
		<PackageReference Include="StackExchange.Redis" Version="2.12.14" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\AuthApi.Application\AuthApi.Application.csproj" />
	  <ProjectReference Include="..\AuthApi.Domain\AuthApi.Domain.csproj" />
	</ItemGroup>
</Project>
